FROM node:14-alpine

# Create app directory
WORKDIR /usr/src/app

# copy node app
COPY declarative-examples/simple-examples/os_version.js ./

# a simple echo from container executed
RUN echo Inside container
